import type { Folder } from "../../../lib/types/folder-structure.interface";
import type { FsdSegment } from "../../../lib/types/fsd.interface";
import type { FsdConfig } from "~/entities/config";

import { DEFAULT_SLICE_FILE_NAME } from "~/shared/lib/constants";

import { fsdSegments } from "../../../lib/types/fsd.interface";
import {
  apiFolderWithTemplates,
  libFolderWithTemplates,
  modelFolderWithTemplates,
  uiFolderWithTemplates,
} from "./folders";
import { publicApiFolderWithTemplates } from "./folders/public-api-folder";

type SegmentList = Record<FsdSegment, Folder>;

export const fsdSegmentListWithTemplates = ({
  configOptions,
  sliceName = DEFAULT_SLICE_FILE_NAME,
}: {
  configOptions: FsdConfig;
  sliceName?: string;
}): SegmentList => {
  const { autogenerate, globalSettings, namingConvention } = configOptions;

  if (!autogenerate) {
    const autogeneratedSegments = fsdSegments.reduce((result, segment) => {
      result[segment] = [];
      return result;
    }, {} as SegmentList);
    return autogeneratedSegments;
  }

  const segments: SegmentList = {
    ui: uiFolderWithTemplates({
      configOptions: globalSettings,
      namingConvention,
      sliceName,
    }),
    model: modelFolderWithTemplates({
      configOptions: globalSettings,
      namingConvention,
      sliceName,
    }),
    lib: libFolderWithTemplates(),
    api: apiFolderWithTemplates({
      configOptions: globalSettings,
      namingConvention,
      sliceName,
    }),
    "public-api": publicApiFolderWithTemplates({
      configOptions: globalSettings,
      namingConvention,
      sliceName,
    }),
  };

  return segments;
};
