import type { FsdConfig } from "~/entities/config/lib/types/config.interface";
import type { Folder } from "~/entities/fsd/lib/types/folder-structure.interface";
import type { FsdSegment } from "~/entities/fsd/lib/types/fsd.interface";

import { generatePublicApiFileName } from "~/entities/fsd/lib/helpers/file-name-helpers";
import { fsdSegments } from "~/entities/fsd/lib/types/fsd.interface";

import {
  apiFolderWithTemplates,
  libFolderWithTemplates,
  modelFolderWithTemplates,
  uiFolderWithTemplates,
} from "./folders";

type SegmentList = Record<FsdSegment, Folder>;

export const fsdSegmentListWithTemplates = ({
  configOptions,
  sliceName = "slice",
}: {
  configOptions: FsdConfig;
  sliceName?: string;
}): SegmentList => {
  const { autogenerate, globalSettings } = configOptions;

  const publicApiFileName = generatePublicApiFileName(
    globalSettings.scriptingLanguage,
  );

  if (!autogenerate) {
    const autogeneratedSegments = fsdSegments.reduce((result, segment) => {
      result[segment] = [];
      return result;
    }, {} as SegmentList);
    return autogeneratedSegments;
  }

  const segments: SegmentList = {
    ui: uiFolderWithTemplates({
      configOptions: globalSettings,
      sliceName,
    }),
    model: modelFolderWithTemplates({
      configOptions: globalSettings,
      sliceName,
    }),
    lib: libFolderWithTemplates({
      configOptions: globalSettings,
      sliceName,
    }),
    api: apiFolderWithTemplates({
      configOptions: globalSettings,
      sliceName,
    }),
    "public-api": [publicApiFileName],
  };

  return segments;
};
